# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f5bfde0d85141fed3d612d92ad7018bf36b96f3c2e6bd7550a21b757e5b5fb5f2dcc24007bcaa89cb24650762f3af35a046d78b7f4f8c3923b0623880a03fa6

test:
  secret_key_base: a109e0d74184b484163c5b4b3a7a1979ce2aaa9a2868fa8d09aaf292e45c5ffa31b9e85039a43db2d6677090be1b6a384743c58b094373fd56190ff75fc87cde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
